ALTER TABLE "OpcoSubmission"
ADD COLUMN "stage" TEXT NOT NULL DEFAULT 'PRISE_EN_CHARGE',
ADD COLUMN "deliveryState" TEXT NOT NULL DEFAULT 'READY',
ADD COLUMN "sendingStartedAt" TIMESTAMP(3),
ADD COLUMN "lastError" TEXT;
